### ISSUE TITLE
Provide docker-compose example?

### ISSUE THREAD

**Issue by NoLooseEnds** [zimme/docker-rar2fs#1]
Hi,

this looks very interesting. I would love to see a bit more documentation.

Would you mind providing an outline of how you use it in a docker-compose file? I presume you use the rar2fs to mount "rar directories" for other docker containers?

Thank you! :)

**Comment by zimme** [comment]
Hey,

Glad this is useful for someone else =)

I haven't used this image in a docker-compose setup yet, but I think it would be something like this.

```yml
version: '3'
services:
  rar2fs:
    image: zimme/rar2fs
    volumes:
      - '<path/to/rared/files>:/source'
      - 'unrared-files:/destination'
volumes:
  unrared-files: null
```

This would mount `<path/to/rared/files>` from the host as a rar2fs mount in the named volume `unrared-files`. Then the named volume `unrared-files` could be used by other services defined in this docker-compose file.

You could also let the named volume `unrared-files` be a path to an empty folder on the host, that way even the host system would be able to access the rar2fs mount.

**Comment by zimme** [comment]
In general the README needs some updated to show more examples of setting the user/group and adding extra groups, using named volumes etc. but I don't know when I'll have time for that.

**Comment by NoLooseEnds** [comment]
Thanks.

I need to go to docker-compose version 3.7 (or go down to v. 2) to allow ```init: true```.

To be able to use rar2fs I also needed:
```
    init: true
    devices:
      - /dev/fuse:/dev/fuse
```

The whole thing looks like:
```
version: '3.7'

services:

  rar2fs:
    container_name: rar2fs
    image: zimme/rar2fs
    init: true
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - '<path/to/rared/files>:/source'
      - 'unrared-files:/destination'

volumes:
  unrared-files: null

```

I've verified that the rar2fs works as expected, it sees the files and "unrars" them. But I'm still having a hard time getting other images accessing the "unrared-files"

This is an example docker-compose file:
```
version: '3.7'

services:

  rar2fs:
    container_name: rar2fs
    image: zimme/rar2fs
    init: true
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - '<path/to/rared/files>:/source'
      - 'unrared-files:/destination'

  containerx:
    container_name: containerx
    restart: always
    image: /path/to/image
    networks:
      - system_default
    volumes:
      - 'unrared-files:/test'
    ports:
      - XXXX:XXXX

volumes:
  unrared-files: null

networks:
  system_default:
    external: true
```

Accessing /test on "containerx" shows zero files, and running the "mount" command shows it mounted as:
```
/dev/root on /test type ext4 (rw,relatime)
```

**Comment by zimme** [comment]
If you run `docker-compose exec rar2fs sh` and run `mount` and `ls -la /destination` is `/destination` mounted as rar2fs and can you see the unrared files?

**Comment by NoLooseEnds** [comment]
Yes, that works. :) I've allready verified that your image works fine, it's just the sharing part that does not work.

**Comment by zimme** [comment]
Ok, I haven't actually tested using a named volume, I have `/destination` mounted to a folder on the host which I bind-mount into my other containers, but I don't see how that would be different than using a named volume as the named volume is just a folder in a "special" docker path on the host.

But maybe this is different when using Docker for Mac/Windows if you're using one of those?

**Comment by NoLooseEnds** [comment]
No, I don't understand it either. But I have little experience with sharing volumes (and not too much experience with docker in general).

I'm running docker on VMWares PhotonOS (as a VM on ESXi)

**Comment by zimme** [comment]
I wonder if you might need to use the `shared`/`rshared`/`<other_option>` option in some way when mounting the named volume in to either the `rar2fs` container or when mounting the named volume into other containers.

**Comment by NoLooseEnds** [comment]
I'll try to look into that. I will report back if/when I find something. Thanks.

**Comment by zimme** [comment]
@NoLooseEnds Did you find any solution to this?

**Comment by NoLooseEnds** [comment]
@zimme No, not gotten around to it (just got myself my first newborn baby) – so not much time for anything else atm.

**Comment by zimme** [comment]
@NoLooseEnds Aah well, I'll try and test a few things when I have time but I had problems using a named volumes when I tested it last too.

Congrats :tada: I'm in the same boat, but my kid is almost 6 months now.

**Comment by zimme** [comment]
Looked into this a bit more...
It seems like volumes in docker uses `rprivate` as the bind-propagation by default and you can't change it.

Wen you bind-mount an empty host folder to the container's `/destination` you need to set the bind-propagation to `shared` for the host folder to contain the unrared files.

I'm guessing this has to do with that the fact that we're mounting something in `/destination` inside the container.

I'll make sure the readme is updated with this new finding and I guess I'll have to complete that docker rar2fs volume plugin I started a few months back but never completed 😝

**Comment by NoLooseEnds** [comment]
Great! I'll give it a spin when I get the time! :)

**Comment by NoLooseEnds** [comment]
Got it to work in docker-compose, and here is the volume section:

```
    volumes:
      - '/path/to/rared/files:/source'
      - type: bind
        bind:
          propagation: shared
        source: /path/to/unrared-files
        target: /destination
```
