### ISSUE TITLE
unrecognized option: foreground

### ISSUE THREAD

**Issue by NoLooseEnds** [zimme/docker-rar2fs#16]
My mount stopped working with the new version I think, and I'm seeing this in the logs: `rar2fs  | rar2fs: unrecognized option: foreground`

I don't have an option that says `foreground`, unless I'm missing something. Been a while since I set up this.

This is my docker compose:
```
  rar2fs:
    container_name: rar2fs
    restart: always
    networks:
      - traefikproxy
    image: zimme/rar2fs
    privileged: true
    init: true
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    volumes:
      - '/mnt/<server>/datapool/download:/source'
      - type: bind
        bind:
          propagation: shared
        source: ./_shared/unrared-files
        target: /destination
```
